source "https://rubygems.org"

gem "abbrev"
gem "fastlane", "~> 2.227.0"
gem "fastlane-plugin-xcconfig"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
