on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./InvestMate

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler & Gems
        run: bundle install

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Set up Tuist project
        run: |
          export PATH="$HOME/.tuist/bin:$PATH" # 터미널에서 tuist 명령어를 인식할 수 있도록 실행 파일 경로를 시스템 PATH에 추가
          tuist install
          tuist generate

      - name: Decode asc_api_key.json
        run: |
          mkdir -p fastlane
          echo "${{ secrets.ASC_API_KEY_JSON_BASE64 }}" | base64 --decode > fastlane/asc_api_key.json

      - name: Decode .env
        run: echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > fastlane/.env

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.3.app/Contents/Developer

      - name: Run Fastlane Release
        run: bundle exec fastlane release
