on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    runs-on: macos-15

    defaults:
      run:
        working-directory: ./InvestMate

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler & Gems
        run: bundle install

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: Set up Tuist project
        run: |
          mise x -- tuist install
          mise x -- tuist generate

      - name: Decode asc_api_key.json
        run: |
          mkdir -p fastlane
          echo "${{ secrets.ASC_API_KEY_JSON_BASE64 }}" | base64 --decode > fastlane/asc_api_key.json

      - name: Decode .env
        run: echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > fastlane/.env

      - name: Select Xcode 16.3
        run: sudo xcode-select -switch /Applications/Xcode_16.3.app

      - name: Check selected Xcode version
        run: xcodebuild -version

      - name: Run Fastlane Release
        run: bundle exec fastlane release

      - name: Commit & Push bumped Version.xcconfig
        if: ${{ success() }}
        run: |
         git config user.name "${{ github.actor }}"
         git config user.email "104732020+joho2022@users.noreply.github.com"
         git add Projects/InvestMate/Configuration/Version.xcconfig
         git commit -m "bump build number [skip ci]"
         git push origin HEAD:main
